import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  const host = process.env.NODE_ENV === "production" ? "prodUrl" : "http://localhost:3000"

  const redirectUri = `${host}/api/callback`

  const scope = [
    "playlist-modify-public",
    "user-top-read",
    "user-read-recently-played",
    "user-read-private",
    "playlist-read-private",
    "streaming"
  ].join("%20")

  const authURL = `https://accounts.spotify.com/authorize?client_id=1588f78a6e2d40bfa8c82c377ba3d37f&response_type=code&redirect_uri=${redirectUri}&scope=${scope}`


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Vibes.infinity</h1>

      <a href={authURL}>Sign in with Spotify</a>
    </>
  )
}
